;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        forward-sexp
        indent-for-tab-command
        indent-new-comment-line
        kill-region
        paredit-backward
        paredit-backward-down
        paredit-backward-kill-word
        paredit-backward-up
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-forward-up
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        end-of-buffer
        ))
